INSERT INTO agences (nom) VALUES ('Paris');
INSERT INTO agences (nom) VALUES ('Lyon');
INSERT INTO agences (nom) VALUES ('Marseille');
INSERT INTO agences (nom) VALUES ('Toulouse');
INSERT INTO agences (nom) VALUES ('Nice');
INSERT INTO agences (nom) VALUES ('Nantes');
INSERT INTO agences (nom) VALUES ('Strasbourg');
INSERT INTO agences (nom) VALUES ('Montpellier');
INSERT INTO agences (nom) VALUES ('Bordeaux');
INSERT INTO agences (nom) VALUES ('Lille');
INSERT INTO agences (nom) VALUES ('Rennes');
INSERT INTO agences (nom) VALUES ('Reims');

INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Martin', 'Alexandre', '0612345678', 'alexandre.martin@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Dubois', 'Sophie', '0698765432', 'sophie.dubois@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Bernard', 'Julien', '0622446688', 'julien.bernard@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Moreau', 'Camille', '0611223344', 'camille.moreau@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Lefèvre', 'Lucie', '0777889900', 'lucie.lefevre@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Leroy', 'Thomas', '0655443322', 'thomas.leroy@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Roux', 'Chloé', '0633221199', 'chloe.roux@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Petit', 'Maxime', '0766778899', 'maxime.petit@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Garnier', 'Laura', '0688776655', 'laura.garnier@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Dupuis', 'Antoine', '0744556677', 'antoine.dupuis@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Lefebvre', 'Emma', '0699887766', 'emma.lefebvre@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Fontaine', 'Louis', '0655667788', 'louis.fontaine@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Chevalier', 'Clara', '0788990011', 'clara.chevalier@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Robin', 'Nicolas', '0644332211', 'nicolas.robin@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Gauthier', 'Marine', '0677889922', 'marine.gauthier@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Fournier', 'Pierre', '0722334455', 'pierre.fournier@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Girard', 'Sarah', '0688665544', 'sarah.girard@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Lambert', 'Hugo', '0611223366', 'hugo.lambert@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Masson', 'Julie', '0733445566', 'julie.masson@email.fr', SHA2('password', 256));
INSERT INTO utilisateurs (nom, prenom, telephone, email, mot_de_passe) VALUES ('Henry', 'Arthur', '0666554433', 'arthur.henry@email.fr', SHA2('password', 256));
